name: Ubuntu

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt install libxinerama-dev libxcursor-dev xorg-dev libglu1-mesa-dev libgl1-mesa-dev
    - name: Install GCC and G++
      run: |
        sudo apt-get install -y gcc-10 g++-10
        echo "CC=/usr/bin/gcc-10" >> $GITHUB_ENV
        echo "CXX=/usr/bin/g++-10" >> $GITHUB_ENV
    - name: Configure project
      run: cmake --preset=default-unix
    - name: Build project
      run: cmake --build build